### ISSUE TITLE
关于删除RISCV中的CD指令

### ISSUE THREAD

**Issue by randyliu2020** [plctlab/PLCT-Open-Reports#111]
您好~：
    我目前在做关于LLVM移植的工作，想问下您，怎么屏蔽掉RISCV中的C，D指令子集？需要关注哪些文件？

**Comment by ChunyuLiao** [comment]
需要关注一下 
1. 文件 ./llvm/lib/Support/RISCVISAInfo.cpp  
2. 目录llvm/lib/Target/RISCV

**Comment by randyliu2020** [comment]
> 需要关注一下
> 
> 1. 文件 ./llvm/lib/Support/RISCVISAInfo.cpp
> 2. 目录llvm/lib/Target/RISCV

你好，目前我对llvm-RISCV的后端还是有些了解，仅修改lib/Target/RISCV/RISCV.td中的
`def FeatureStdExtD
    : SubtargetFeature<"d", "HasStdExtD", "true",
                       "'D' (Double-Precision Floating-Point)",
                       [FeatureStdExtF]>;
def HasStdExtD : Predicate<"Subtarget->hasStdExtD()">,
                           AssemblerPredicate<"FeatureStdExtD">;`
true为false是否可以达到预期的效果？还是要把关联的这些全部删掉？并且同时需要删掉64位指令，同样修改true为false是否可以完成？

**Comment by ChunyuLiao** [comment]
> > 需要关注一下
> > 
> > 1. 文件 ./llvm/lib/Support/RISCVISAInfo.cpp
> > 2. 目录llvm/lib/Target/RISCV
> 
> 你好，目前我对llvm-RISCV的后端还是有些了解，仅修改lib/Target/RISCV/RISCV.td中的 `def FeatureStdExtD : SubtargetFeature<"d", "HasStdExtD", "true", "'D' (Double-Precision Floating-Point)", [FeatureStdExtF]>; def HasStdExtD : Predicate<"Subtarget->hasStdExtD()">, AssemblerPredicate<"FeatureStdExtD">;` true为false是否可以达到预期的效果？还是要把关联的这些全部删掉？并且同时需要删掉64位指令，同样修改true为false是否可以完成？

两种方式都可以尝试一下呀，编译运行一版很快就有结果了， 遇到什么问题再进一步讨论

**Comment by lazyparser** [comment]
一年半过去了，看起来问题已经拒绝了，关闭了哈～ 有问题欢迎开心issue提问
