### ISSUE TITLE
Gem5模拟并行系统的principle

### ISSUE THREAD

**Issue by linbaiwpi** [plctlab/PLCT-Open-Reports#122]
想询问下，Gem5是如何用顺序执行的软件来实现硬件的并行的呢？

**Comment by ksco** [comment]
谢邀。

首先说明两个概念：
1. Simulated performance 指的是被模拟的程序的性能
2. Simulator performance 指的是模拟器的性能

我们在使用 gem5 这种模拟器的时候，通常关心的是 Simulated performance，即 gem5 运行完成后，产生的 stats 数据中的 tick 值，而并不关心这个模拟过程我们的电脑上实际花了多久。

gem5 是一个基于离散事件的模拟器，每个事件都会在某个 tick 值被执行，同一个 tick 值的事件，在被模拟的程序看来，就是同时执行的。当然实际上在 gem5 中，他们是一条一条执行的，但这并不影响正确性，也不影响 Simulated performance。
