### ISSUE TITLE
gem5 RVV向量扩展多核下配置的正确方法

### ISSUE THREAD

**Issue by yuxuan-z19** [plctlab/PLCT-Open-Reports#133]
因为课题需求，现在我在gem5上配置 带 RVV VectorEngine的多核硬件，每一个CPU内部都有一个RVV VectorEngine，并且是接到L1D Cache上（即没有VectorCache），配置脚本 [是这个](https://github.com/yuxuan-z19/gem5/blob/master/thrusterV2/thruster.py)

预期的配置如下
![config](https://user-images.githubusercontent.com/68550432/166683165-6cd4a2a5-bca8-4ee0-a03b-4b6df6e5c004.png)

然而我在运行一个RVV向量加法程序`a + b = c`时，发生计算错误：`c`没有被赋值  

怀疑有可能是配置的方式有问题，可以的话想向各位请教正确的配置方法！！

**Comment by ksco** [comment]
这个分支我们现在已经不再维护了哈，新版在 https://github.com/plctlab/plct-gem5 rvv-cpu 分支，目前支持的指令数量还不多。
