### ISSUE TITLE
关于GNU的测试框架的提问

### ISSUE THREAD

**Issue by Stark-qan** [plctlab/PLCT-Open-Reports#145]
请问GNU的测试框架的官方详细说明在哪里呀？
我对GNU官方测试用例的指示符“dg-skip-if”的具体书写格式和模板还是不太明白；虽然您的视频里有过讲解，如下图：
![image](https://user-images.githubusercontent.com/48877981/194817260-6fcfd234-12d1-4b93-af2c-62441ca572d0.png)
但我在运行RVV相关的测试时遇到了错误时：
![image](https://user-images.githubusercontent.com/48877981/194817715-e99af251-e595-47ae-8e29-eade1158c582.png)
测试用例是这么写的：
![image](https://user-images.githubusercontent.com/48877981/194817801-eea7be58-b2c8-4614-b84c-23e7292cf944.png)
就不太明白它pass或fail的标准是什么了。

**Comment by runningsnake** [comment]
dejagnu测试原理是把编译输出后的结果与expect 结果相比较，一致就输出0，不一致输出1，根据比较结果利用fail/pass函数传递测试结果，如图所示。
![image](https://user-images.githubusercontent.com/43627091/194820376-52669082-fe9a-4605-bc60-393ca1a3da7d.png)
但是我到现在也没有看到所谓的expect result。你测试错误原因好像是测评平台的原因，可能是在x86主机上测试riscv可执行测试，移到板子上试试或者用模拟器？

**Comment by Stark-qan** [comment]
是不是因为我在运行测试工具的时候用的命令里没有指定模拟器？
我测试命令是：
`make newlib`
修改Makefile，指定运行的测试目录
`make report-newlib`
而是应该把这后一条改成：`make report-newlib SIM=qemu`？
参考：https://github.com/riscv-collab/riscv-gnu-toolchain/issues/814

**Comment by Stark-qan** [comment]
> > 请问GNU的测试框架的官方详细说明在哪里呀？ 我对GNU官方测试用例的指示符“dg-skip-if”的具体书写格式和模板还是不太明白；虽然您的视频里有过讲解，如下图： ![image](https://user-images.githubusercontent.com/48877981/194817260-6fcfd234-12d1-4b93-af2c-62441ca572d0.png)
> 
> 你好，dejagnu测试框架的官方说明可以参考：https://gcc.gnu.org/onlinedocs/gccint/Test-Directives.html#Test-Directives
> 
> > 但我在运行RVV相关的测试时遇到了错误时： ![image](https://user-images.githubusercontent.com/48877981/194817715-e99af251-e595-47ae-8e29-eade1158c582.png) 测试用例是这么写的： ![image](https://user-images.githubusercontent.com/48877981/194817801-eea7be58-b2c8-4614-b84c-23e7292cf944.png) 就不太明白它pass或fail的标准是什么了。
> 
> 这里的[dg-skip-if](https://gcc.gnu.org/onlinedocs/gccint/Selectors.html#Selectors)常用来跳过某些不支持的架构, 通过截图可以看到错误类型全是`execution test`的失败，意味着预期的运行结果与实际运行结果不一致，通常这类错误与编译器无关，建议检查使用的模拟器是否支持了RVV并且打开了RVV的对应开关。
> 
> （回归测试中模拟器的参数设置位于`$TOOLCHAIN/scripts/wrapper`目录下对应使用的模拟器中，默认使用qemu）

好的！除了遇到了execution test的失败，还遇到了一些`test for excess errors` ：
![image](https://user-images.githubusercontent.com/48877981/194824888-e1593ae5-9488-45c5-a8cf-f353f2a4d3d0.png)
这个也是跟模拟器有关吗？

**Comment by pz9115** [comment]
excess errors表示编译器内部错误，具体错误情况可以查看`$TOOLCHAIN/build-gcc-*-stage2/gcc/testsuite/gcc/gcc.log中的详细错误记录

**Comment by Stark-qan** [comment]
> > 请问GNU的测试框架的官方详细说明在哪里呀？ 我对GNU官方测试用例的指示符“dg-skip-if”的具体书写格式和模板还是不太明白；虽然您的视频里有过讲解，如下图： ![image](https://user-images.githubusercontent.com/48877981/194817260-6fcfd234-12d1-4b93-af2c-62441ca572d0.png)
> 
> 你好，dejagnu测试框架的官方说明可以参考：https://gcc.gnu.org/onlinedocs/gccint/Test-Directives.html#Test-Directives
> 
> > 但我在运行RVV相关的测试时遇到了错误时： ![image](https://user-images.githubusercontent.com/48877981/194817715-e99af251-e595-47ae-8e29-eade1158c582.png) 测试用例是这么写的： ![image](https://user-images.githubusercontent.com/48877981/194817801-eea7be58-b2c8-4614-b84c-23e7292cf944.png) 就不太明白它pass或fail的标准是什么了。
> 
> 这里的[dg-skip-if](https://gcc.gnu.org/onlinedocs/gccint/Selectors.html#Selectors)常用来跳过某些不支持的架构, 通过截图可以看到错误类型全是`execution test`的失败，意味着预期的运行结果与实际运行结果不一致，通常这类错误与编译器无关，建议检查使用的模拟器是否支持了RVV并且打开了RVV的对应开关。
> 
> （回归测试中模拟器的参数设置位于`$TOOLCHAIN/scripts/wrapper`目录下对应使用的模拟器中，默认使用qemu）

我测试命令是：（参考：https://github.com/riscv-collab/riscv-gnu-toolchain/issues/814）
`make newlib`
`make report-newlib SIM=spike `
而且进入`$TOOLCHAIN/scripts/wrapper`里修改了riscv64-unknown-linux-gnu-run文件，打开了RVV开关（加上了字母‘V’）如图：
![image](https://user-images.githubusercontent.com/48877981/194836623-a4b2d077-0902-4c90-9337-afb0d6fbfde3.png)
结果运行还是出现：execution test的失败

**Comment by pz9115** [comment]
> excess errors表示编译器内部错误，具体错误情况可以查看`$TOOLCHAIN/build-gcc-*-stage2/gcc/testsuite/gcc/gcc.log`中的详细错误记录

可以提供一下详细的错误log和$TOOLCHAIN中spike的git log版本吗？

**Comment by Stark-qan** [comment]
> > excess errors表示编译器内部错误，具体错误情况可以查看`$TOOLCHAIN/build-gcc-*-stage2/gcc/testsuite/gcc/gcc.log`中的详细错误记录
> 
> 可以提供一下详细的错误log和$TOOLCHAIN中spike的git log版本吗？
[gcc.log](https://github.com/plctlab/PLCT-Open-Reports/files/9744915/gcc.log)
[gcc-sum.txt](https://github.com/plctlab/PLCT-Open-Reports/files/9744927/gcc-sum.txt)
$TOOLCHAIN中spike的git log版本不知道放在哪里，在$TOOLCHAIN/scripts/wrapper/spike里只有一个文件：
[riscv64-unknown-linux-gnu-run.txt](https://github.com/plctlab/PLCT-Open-Reports/files/9744945/riscv64-unknown-linux-gnu-run.txt) 
（转成了.txt文件不然没法上传）

**Comment by Stark-qan** [comment]
> > excess errors表示编译器内部错误，具体错误情况可以查看`$TOOLCHAIN/build-gcc-*-stage2/gcc/testsuite/gcc/gcc.log`中的详细错误记录
> 
> 可以提供一下详细的错误log和$TOOLCHAIN中spike的git log版本吗？

我改用qemu，然后在$TOOLCHAIN/scripts/wrapper/qemu/riscv64-unknown-linux-gnu-run里添加了支持RVV的选项：
![image](https://user-images.githubusercontent.com/48877981/194855210-6f5cbea7-b07d-400f-9684-e563fa0ed74b.png)
就解决了execution test的失败。
但是仍然不知道spike里的RVV开关如何打开，我在外面调用工具链里的spike可以在使用了--isa=RV64GCV选项之后是支持RVV的：
![image](https://user-images.githubusercontent.com/48877981/194855785-9105cfde-85cf-44a8-85c4-e70372bfd1f5.png)

**Comment by pz9115** [comment]
> > > excess errors表示编译器内部错误，具体错误情况可以查看`$TOOLCHAIN/build-gcc-*-stage2/gcc/testsuite/gcc/gcc.log`中的详细错误记录
> > 
> > 
> > 可以提供一下详细的错误log和$TOOLCHAIN中spike的git log版本吗？
> > [gcc.log](https://github.com/plctlab/PLCT-Open-Reports/files/9744915/gcc.log)

我查看了错误的log文件，似乎没有选取spike作为模拟器，仍在使用qemu进行测试

> 引用自gcc.log
> /home/xuqian/workspace/study/tool/riscv-gnu-toolchain/build/../scripts/wrapper/qemu/riscv64-unknown-elf-run: line 15:  6560 Illegal instruction     qemu-riscv$xlen -r 5.10 "${qemu_args[@]}" -L ${RISC_V_SYSROOT} "$@"
FAIL: gcc.target/riscv/rvv/examples/rvv_branch.c -march=rv64gcv  -O2  execution test

> > [gcc-sum.txt](https://github.com/plctlab/PLCT-Open-Reports/files/9744927/gcc-sum.txt)
> > $TOOLCHAIN中spike的git log版本不知道放在哪里，在$TOOLCHAIN/scripts/wrapper/spike里只有一个文件：
> > [riscv64-unknown-linux-gnu-run.txt](https://github.com/plctlab/PLCT-Open-Reports/files/9744945/riscv64-unknown-linux-gnu-run.txt)
> > （转成了.txt文件不然没法上传）

**Comment by Stark-qan** [comment]
是的，我们根据指导查看了错误的log文件，发现执行错误的原因是qemu和spike的版本太低了，不支持RVV，因为我们当时没有follow最新版本的GCC。

**Comment by Stark-qan** [comment]
但是我们测试了rvv的全部测试用例，发现只有以下三个文件夹里/文件的FAIL：
gcc.target/riscv/rvv/intrinsic/a1u/
gcc.target/riscv/rvv/intrinsic/custom/vlx2-on-rv32/vsetvl-opt.c
gcc.target/riscv/rvv/vectorization/
我们没有找到这些测试用例的详细说明，请问这应该如何解决？是工具链的配置有问题还是应该忽略这些错误？
[gcc.zip](https://github.com/plctlab/PLCT-Open-Reports/files/9761007/gcc.zip)

**Comment by pz9115** [comment]
看起来是intrinsic和autovectorization的测试用例错误，需要确认一下rvv-gcc的版本，目前上游版本中应该还未完全支持这些特性

**Comment by Stark-qan** [comment]
我们目前使用的是riscv-gcc-rvv-next分支，这些错误应该是正常现象嘛？

**Comment by pz9115** [comment]
应该是正常的，该分支仍在更新中，还没有支持全部RVV特性

**Comment by Stark-qan** [comment]
老师您好，请问这个测试报告里面的`unresolved`和`unsupported`意味着什么呀？
```
# of unresolved testcases	        41802
# of unsupported tests		175
```

**Comment by pz9115** [comment]
Unsupported 表示在运行该测试用例时由于未满足测试用例设置的条件，所以判断为不支持，例如{target riscv*}
Unresolved 比较少见，表明无法判断测试通过还是失败，标记为未解决，等待处理

**Comment by Stark-qan** [comment]
我们的配置选项是：`./configure --prefix=/home/out --with-arch=rv64gcv_zba_zbb_zbc_zbs --with-abi=lp64d`
在测试的时候，对于RVB的测试用例的结果是：全部PASS，但是有unsupported如下：
```
UNSUPPORTED: gcc.target/riscv/zbs-bset.c   -O0 
UNSUPPORTED: gcc.target/riscv/zbs-binv.c   -O0
UNSUPPORTED: gcc.target/riscv/zbs-bext.c   -O0
UNSUPPORTED: gcc.target/riscv/zbs-bclr.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbs-bclr.c   -O0
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-03.c   -O0
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-02.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-02.c   -O3 -g
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-02.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-02.c   -O3 -g
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-01.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-01.c   -O3 -g
UNSUPPORTED: gcc.target/riscv/zbb-rol-ror-01.c   -O0
UNSUPPORTED: gcc.target/riscv/zbb-min-max.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbb-min-max.c   -O3 -g
UNSUPPORTED: gcc.target/riscv/zbb-andn-orn-xnor-02.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbb-andn-orn-xnor-02.c   -O3 -g
UNSUPPORTED: gcc.target/riscv/zbb-andn-orn-xnor-02.c   -O0
UNSUPPORTED: gcc.target/riscv/zbb-andn-orn-xnor-01.c  -Og -g
UNSUPPORTED: gcc.target/riscv/zbb-andn-orn-xnor-01.c   -O3 -g
UNSUPPORTED: gcc.target/riscv/zbb-andn-orn-xnor-01.c   -O0
UNSUPPORTED: gcc.target/riscv/zba-zextw.c   -O0
UNSUPPORTED: gcc.target/riscv/zba-slliuw.c   -O1
UNSUPPORTED: gcc.target/riscv/zba-slliuw.c   -O0
UNSUPPORTED: gcc.target/riscv/zba-shNadd-03.c   -O0
UNSUPPORTED: gcc.target/riscv/zba-shNadd-02.c   -O0
UNSUPPORTED: gcc.target/riscv/zba-shNadd-01.c   -O0
UNSUPPORTED: gcc.target/riscv/zba-adduw.c   -O0
```
我抽了zba-adduw.c这个文件单独编译一下，发现并没有自动地产生预期的指令：`add.uw`
但是我手写的带有B-扩展指令`add.uw`的汇编文件是可以被识别的
请问这是因为我配置选项少写了或有其他错误，还是目前官方对B扩展只是在汇编层面上的支持，没有自动bitmanip化？

**Comment by pz9115** [comment]
上游已经支持RVB的自动生成了,这个仓库基于上游开发应该是支持的

**Comment by Stark-qan** [comment]
> 但是我们测试了rvv的全部测试用例，发现只有以下三个文件夹里/文件的FAIL： gcc.target/riscv/rvv/intrinsic/a1u/ gcc.target/riscv/rvv/intrinsic/custom/vlx2-on-rv32/vsetvl-opt.c gcc.target/riscv/rvv/vectorization/ 我们没有找到这些测试用例的详细说明，请问这应该如何解决？是工具链的配置有问题还是应该忽略这些错误？ [gcc.zip](https://github.com/plctlab/PLCT-Open-Reports/files/9761007/gcc.zip)

关于`gcc.target/riscv/rvv/intrinsic/a1u/`的FAIL我们做了修复，准备推上去，然后被告知a1u是旧版本RVV的测试用例，相关新版本的测试用例放在了alu里，a1u应当删除，所以我们把删除的推上去了。

**Comment by Stark-qan** [comment]
> 上游已经支持RVB的自动生成了,这个仓库基于上游开发应该是支持的

是的，我发现没有自动化的原因是没加优化选项。现在得到了自动生成的B扩展代码。
