### ISSUE TITLE
cmo 中flush的疑问

### ISSUE THREAD

**Issue by dongyongtao** [plctlab/PLCT-Open-Reports#150]
20220105-史玉龙-CMO指令介绍.pdf

关于这个分享，有几个疑问想请教下：
*  ppt中说 flush operation——执行invalidate operation之后的clean operation，invalidate和clean的顺序是不是反了？

    这里我看了spec，原文是
    A flush operation atomically performs a clean operation followed by an invalidate operation

    followed by，应该是表明先clean 再 invalidate。先把内容刷到memory，在inval cache。

 * 另外，这里的flush是为了【原子性的执行】 先clean 再 invalidate，在arm中的理解 flush只是执行一个写入传
    输到另一个缓存或者内存，所以在arm中的flush应该是等同riscv cmo中的clean吧，感觉有点怪

**Comment by yulong-plct** [comment]
根据spec的描述，flush=invalid + clean的组合操作，当时理解的不够深入。
关于arm的flush是否等同于cmo的clean，操作的行为来看似乎是一样的，但是不确定二者是等同的。

**Comment by lazyparser** [comment]
关闭看起来已经得到解答的问题。

如果还需要继续讨论的话随时欢迎reopen。
