### ISSUE TITLE
OpenDay2024  PLCT2024.pdf 中的LLVM测试验证文档链接被遮挡

### ISSUE THREAD

**Issue by zqb-all** [plctlab/PLCT-Open-Reports#199]
1. [pdf](https://github.com/plctlab/PLCT-Open-Reports/blob/master/OpenDay2024/01-%E9%82%B1%E5%90%89-PLCT2024.pdf)中的链接被挡住了 
![image](https://github.com/user-attachments/assets/6049bec0-2978-4133-97f8-a85bd88b6bdd)

2. 完整的链接是[这个](https://docs.google.com/spreadsheets/d/19UF1KTO1swbKNjx2fNvMiltVJgdlEDTzy7c3Z_d-PtA)

**Comment by lazyparser** [comment]
感谢指正！
