### ISSUE TITLE
王建中同学在讲解RVV指令时提到一个文件，《增加RVV指令路线图》能不能发一下，没有找到

### ISSUE THREAD

**Issue by buggfg** [plctlab/PLCT-Open-Reports#89]
https://www.bilibili.com/video/av543231854/
<img width="730" alt="10876937" src="https://user-images.githubusercontent.com/37240925/118905076-a104d180-b94d-11eb-92fe-49314a203ac8.png">
十分感谢

**Comment by luyahan** [comment]
已pr到v8仓库
https://github.com/plctlab/v8-internals/blob/master/add_rvv.md
