### ISSUE TITLE
建议整理一下目录结构

### ISSUE THREAD

**Issue by darionyaphet** [plctlab/PLCT-Open-Reports#91]
建议整理一下目录结构，简单分下类，以后PPT越来越多，现在这样可能会不太好找

**Comment by lazyparser** [comment]
嗯，确实，后续可以按照基础分类来进行。

已经上传的slides比较犹豫要不要更新位置或名字，因为已经有外部链接引用了。

**Comment by darionyaphet** [comment]
或者我们重新启动一个 目录 按照某些分类方法 存PPT地址？

**Comment by lazyparser** [comment]
这是个好主意 👍

周末我来整理下先，缩短下README的长度

**Comment by darionyaphet** [comment]
> 这是个好主意 👍
> 
> 周末我来整理下先，缩短下README的长度

是… 现在的ReadME 是长了点 ...

**Comment by hyf6661669** [comment]
你好，是不是可考虑按照月份来划分。。

**Comment by darionyaphet** [comment]
> 你好，是不是可考虑按照月份来划分。。

通常来说 是记不得月份的……

**Comment by Taowyoo** [comment]
可以尝试放到github wiki里，wiki有侧边栏支持目录

**Comment by lazyparser** [comment]
经过一年多的观察，现在觉得已经暴露的外部链接并不多见。后续会逐步

1. 去掉文件名字中的非ASCII，改成全英文。
2. 将所有的幻灯片移动到一个子目录下 slides/

**Comment by lazyparser** [comment]
已经整理了（部分）
