### ISSUE TITLE
如何编译生成带intrinsic的llvm-ir, @llvm.riscv.xxx

### ISSUE THREAD

**Issue by lyuchuny3** [plctlab/PLCT-Open-Reports#94]
你好，

我看到目前前端clang从riscv  intrinsic已经可以编译成llvm ir, 那么后端基于带riscv intrinsic的llvm ir (@llvm.riscv.xxx)可以顺利编译成RISCV 可执行文件吗, 编译命令 和 目标target参数如何设置呢

![image](https://user-images.githubusercontent.com/15851888/121154364-81403980-c879-11eb-8634-028207f3167e.png)

**Comment by luxufan** [comment]
Hi,
您需要预先构建一套GNU的toolchain，这是链接： https://github.com/riscv/riscv-gnu-toolchain 

随后clang 编译时带上参数: -gcc-toolchain=<path to gnu toolchain> --sysroot=<path to gnu sysroot>
